# Generated by Django 4.0.4 on 2022-05-03 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(max_length=200)),
                ('agencia_origem', models.CharField(max_length=200)),
                ('conta_origem', models.CharField(max_length=200)),
                ('banco_destino', models.CharField(max_length=200)),
                ('agencia_destino', models.CharField(max_length=200)),
                ('conta_destino', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('data_transacao', models.DateTimeField(unique_for_date=True)),
                ('data_importacao', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
