# Generated by Django 4.0.4 on 2022-05-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='agencia_destino',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='agencia_origem',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='banco_origem',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta_destino',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta_origem',
            field=models.CharField(max_length=7),
        ),
    ]
