# Generated by Django 4.0.4 on 2022-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_alter_transacao_agencia_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_transacao',
            field=models.DateTimeField(),
        ),
    ]
