# Generated by Django 4.0.4 on 2022-05-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_alter_transacao_data_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_importacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
